FROM debian:wheezy

<!-- @import maintainer -->
ENV PHP_VERSION 5.3.29
ENV PHP_INI_DIR /usr/local/etc/php
ENV PHP_URL "http://museum.php.net/php5/php-$PHP_VERSION.tar.bz2"
ENV PHP_EXTRA_EXT ""
ENV EXTRA_PACKAGES ""
ENV XDEBUG_BRANCH "xdebug_2_2"
<!-- @import debian/ci-installation -->
